apiVersion: apps/v1
kind: Deployment
metadata:
  name: score-ms
  namespace: vehicle-platform
  labels:
    app: score-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: score-ms
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: score-ms
    spec:
      containers:
        - name: score-ms
          image: scoremsjava.azurecr.io/score-ms:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: score-ms-config
            - secretRef:
                name: servicebus-secrets
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"