apiVersion: v1
kind: Service
metadata:
  name: score-ms-service
  namespace: vehicle-platform
  labels:
    app: score-ms
spec:
  type: LoadBalancer
  ports:
    - port: 8089
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: score-ms